//Local Host

###Get all documents 
GET http://localhost:3000/paneldocs 

###Get one document by id 
GET http://localhost:3000/paneldocs/652b37c30387940cbf3b7409

###Create document 
POST http://localhost:3000/paneldocs HTTP/1.1 
Content-Type: application/json

{
    "title": "Alarmnet Activation",
    "category": "cellular",
    "manufacturer": "Alarmnet",
    "model": "",
    "docType": "training",
    "description": "Instructions for activating an alarmnet dialer",
    "URL": "http://www.com/ActivateAlarmnet",
    "dateAdded": "10/28/2023",
    "user": "Anna"
}

### Update Document 
PUT http://localhost:3000/paneldocs/653d20ee929772dd2722f409 HTTP/1.1 
Content-Type: application/json

{
  "title": "Alarmnet Activation",
  "category": "cellular dialer",
  "manufacturer": "Alarmnet",
  "model": "",
  "docType": "training",
  "description": "Instructions for activating an alarmnet dialer",
  "URL": "http://www.com/ActivateAlarmnet",
  "dateAdded": "10/28/2023",
  "user": "Anna"
}

### Delete a Document

DELETE http://localhost:3000/paneldocs/652b31bb4f1009f5f51897e2 HTTP/1.1


//--------------------------------------------------------------------
//Users

### Get all Users
GET http://localhost:3000/users

###Get one user by id 
GET http://localhost:3000/users/654638fae725ce53627d49bc

###Create user 
POST http://localhost:3000/users/ HTTP/1.1 
Content-Type: application/json

{
    "firstName": "Tyler",
    "lastName": "Ross",
    "email": "tyty@email.com",
    "password": "sp33dybo1!"
}

### Delete a Document

DELETE http://localhost:3000/users/654637c4e725ce53627d49bb HTTP/1.1


//Render Routes

###Get all documents 
GET http://training-docs.onrender.com/paneldocs

###Get one document by id 
GET https://training-docs.onrender.com/paneldocs/6532d9ce6468ea420f786cd

###Create document 
POST https://training-docs.onrender.com/paneldocs HTTP/1.1 
Content-Type: application/json

{
    "title": "How to Address a DMP keypad",
    "category": "alarm panel",
    "manufacturer": "DMP",
    "model": "XR-Series",
    "docType": "training",
    "description": "Instructions for addressing a DMP keypad",
    "URL": "http://www.com/testadddress",
    "dateAdded": "10/14/23",
    "user": "Anna"
}

### Update Contact 
PUT https://training-docs.onrender.com/paneldocs/652b2abf1a76ebe384b97396/ HTTP/1.1 
Content-Type: application/json

{
    "title": "How to Address a DMP keypad",
    "category": "alarm panel",
    "manufacturer": "DMP",
    "model": "XR-Series",
    "docType": "training",
    "description": "Instructions for addressing a DMP keypad",
    "URL": "T://emc/programming/keypad-instructions.doc",
    "dateAdded": "10/14/23",
    "user": "Anna"
}

### Delete a contact

DELETE https://training-docs.onrender.com/paneldocs/6532ee73838389e9fcb890da HTTP/1.1
